version: '3.2'
services:
  webserver:
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal